#!/usr/bin/env python3
"""Reader-facing manuscript and pre-candidate review authority for Core v2.

This module does not write publication prose. ChatGPT authors the reader-facing
source directly. The module binds those exact bytes to the approved
Architecture/Profile and records semantic/editorial and visual reviews of the
exact source/PDF pair. Reader-manuscript validation resolves claimed LONGFORM
coverage to exact reader blocks; substantive adequacy remains semantic-review
responsibility and is recorded against those exact blocks.
"""
from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from pypdf import PdfReader

from scripts import survey_production_v2 as core
from scripts import survey_quality_v2 as quality
from scripts import survey_reader_fidelity_v2 as fidelity
from scripts import survey_reader_surface_gate_v2 as surface_gate
from scripts import survey_schema_v2 as schema_gate

MANUSCRIPT_SCHEMA = Path("schemas/reader-manuscript-v2.schema.json")
REVIEW_SCHEMA = Path("schemas/publication-review-record-v2.schema.json")
ARCHITECTURE_SCHEMA = Path("schemas/issue-architecture-v2.schema.json")
ARCHITECTURE_APPROVAL_SCHEMA = Path("schemas/architecture-approval-record-v2.schema.json")
REVIEW_CONTRACT = Path("config/publication-review-v2.json")


def _rel(repo_root: Path, path: Path) -> str:
    root = repo_root.resolve()
    resolved = path.resolve()
    try:
        return str(resolved.relative_to(root)).replace("\\", "/")
    except ValueError as exc:
        raise ValueError(f"reader-publication artifact must be repository-local: {path}") from exc


def _input_path(repo_root: Path, path: Path | str) -> Path:
    value = Path(path)
    return value if value.is_absolute() else repo_root / value


def _safe_file(repo_root: Path, path: Path, label: str) -> Path:
    rel = _rel(repo_root, path)
    resolved = core.repo_local_path(repo_root, rel, label)
    if resolved.is_symlink() or not resolved.is_file():
        raise ValueError(f"{label} missing or unsafe: {rel}")
    return resolved


def _artifact(repo_root: Path, path: Path) -> dict[str, str]:
    value = _safe_file(repo_root, path, "artifact")
    return {"path": _rel(repo_root, value), "sha256": core.sha256_file(value)}


def _sized_artifact(repo_root: Path, path: Path) -> dict[str, Any]:
    value = _safe_file(repo_root, path, "sized artifact")
    return {
        "path": _rel(repo_root, value),
        "sha256": core.sha256_file(value),
        "byte_count": value.stat().st_size,
    }


def _exact_pdf_page_count(path: Path) -> int:
    """Derive page count from the exact reviewed PDF bytes, fail-closed.

    Publication PDFs are generated by LuaLaTeX and may place Page dictionaries
    inside PDF object streams. Use a standards-aware parser rather than scanning
    raw object text so the authority works on the production PDF encoding while
    still deriving the count from the exact repository-resident bytes.
    """
    try:
        reader = PdfReader(path, strict=True)
        if reader.is_encrypted:
            raise ValueError("reviewed publication PDF must not be encrypted")
        page_count = len(reader.pages)
    except ValueError:
        raise
    except Exception as exc:
        raise ValueError("reviewed publication PDF is not deterministically inspectable") from exc
    if page_count < 1:
        raise ValueError("reviewed publication PDF contains no pages")
    return page_count


def _validate_artifact_ref(
    repo_root: Path,
    ref: dict[str, Any],
    label: str,
    *,
    sized: bool = False,
) -> Path:
    expected = {"path", "sha256", "byte_count"} if sized else {"path", "sha256"}
    if not isinstance(ref, dict) or set(ref) != expected:
        raise ValueError(f"{label} authority fields invalid")
    path = core.repo_local_path(repo_root, ref["path"], label)
    if path.is_symlink() or not path.is_file() or core.sha256_file(path) != ref["sha256"]:
        raise ValueError(f"{label} authority drift")
    if sized and path.stat().st_size != ref["byte_count"]:
        raise ValueError(f"{label} byte_count drift")
    return path


def _profile(repo_root: Path, profile_path: Path, issue_id: str) -> tuple[Path, dict[str, Any]]:
    path = _safe_file(repo_root, profile_path, "Production Profile")
    profile = core.load_json(path)
    cfg = core.load_json(repo_root / core.DEFAULT_CONFIG)
    errors = core.validate_profile(profile, cfg)
    if errors:
        raise ValueError("Production Profile invalid: " + "; ".join(errors))
    if profile.get("issue_id") != issue_id:
        raise ValueError("Production Profile issue identity mismatch")
    return path, profile


def _architecture_authority(
    repo_root: Path,
    issue_id: str,
    profile: dict[str, Any],
    architecture_path: Path,
    approval_path: Path,
) -> tuple[Path, dict[str, Any], Path]:
    architecture_file = _safe_file(repo_root, architecture_path, "Issue Architecture")
    architecture = schema_gate.load_and_validate_json(
        architecture_file,
        repo_root / ARCHITECTURE_SCHEMA,
        label="Issue Architecture",
    )
    if (
        architecture.get("issue_id") != issue_id
        or architecture.get("research_profile") != profile.get("research_profile")
        or architecture.get("publication_profile") != profile.get("publication_profile")
    ):
        raise ValueError("Issue Architecture/Profile identity mismatch")
    approval_file = _safe_file(repo_root, approval_path, "Architecture Approval")
    approval = schema_gate.load_and_validate_json(
        approval_file,
        repo_root / ARCHITECTURE_APPROVAL_SCHEMA,
        label="Architecture Approval",
    )
    if approval.get("issue_id") != issue_id or approval.get("decision") != "APPROVED":
        raise ValueError("Architecture Approval identity/decision invalid")
    if approval.get("architecture_sha256") != core.sha256_file(architecture_file):
        raise ValueError("Architecture Approval does not bind exact Architecture bytes")
    return architecture_file, architecture, approval_file


def _required_architecture_coverage(architecture: dict[str, Any]) -> set[tuple[str, str]]:
    required: set[tuple[str, str]] = set()
    for package in architecture.get("packages", []):
        package_id = package["package_id"]
        for requirement in package.get("must_cover_requirements", []):
            key = (package_id, requirement)
            if key in required:
                raise ValueError(f"Architecture duplicates must-cover requirement: {package_id}/{requirement}")
            required.add(key)
    return required


def _required_reader_requirements(profile: dict[str, Any]) -> set[str]:
    required = {"FINAL_SYNTHESIS"}
    if profile.get("research_profile") == "WEEKLY":
        required.add("WEEKLY_COMMUNITY_MOVEMENT")
    return required


def _validate_manifest_semantics(
    repo_root: Path,
    payload: dict[str, Any],
    suppressions: list[dict[str, Any]] | None = None,
) -> tuple[Path, dict[str, Any], Path]:
    issue_id = payload["issue_id"]
    profile_path = _validate_artifact_ref(
        repo_root,
        payload["production_profile"],
        "Reader Production Profile",
    )
    _, profile = _profile(repo_root, profile_path, issue_id)
    if (
        payload["research_profile"] != profile["research_profile"]
        or payload["publication_profile"] != profile["publication_profile"]
    ):
        raise ValueError("Reader Manifest Profile identity mismatch")

    architecture_path = _validate_artifact_ref(
        repo_root,
        payload["architecture"],
        "Reader Architecture",
    )
    approval_path = _validate_artifact_ref(
        repo_root,
        payload["architecture_approval"],
        "Reader Architecture Approval",
    )
    _, architecture, _ = _architecture_authority(
        repo_root,
        issue_id,
        profile,
        architecture_path,
        approval_path,
    )

    source_path = _validate_artifact_ref(
        repo_root,
        payload["primary_source"],
        "Reader primary source",
        sized=True,
    )
    survey_root = core.repo_local_path(
        repo_root,
        profile["paths"]["survey_root"],
        "paths.survey_root",
    )
    if source_path.resolve() != (survey_root / "main.tex").resolve():
        raise ValueError("Reader primary source must be the canonical survey_root/main.tex")

    seen_supporting: set[str] = set()
    for row in payload["supporting_files"]:
        path = _validate_artifact_ref(
            repo_root,
            {
                "path": row["path"],
                "sha256": row["sha256"],
                "byte_count": row["byte_count"],
            },
            f"Reader supporting file {row['role']}",
            sized=True,
        )
        rel = _rel(repo_root, path)
        if rel == payload["primary_source"]["path"] or rel in seen_supporting:
            raise ValueError("Reader source file authority must not contain duplicate paths")
        seen_supporting.add(rel)

    expected_coverage = _required_architecture_coverage(architecture)
    actual_coverage: set[tuple[str, str]] = set()
    for row in payload["architecture_coverage"]:
        key = (row["package_id"], row["requirement"])
        if key in actual_coverage:
            raise ValueError(f"Reader Architecture coverage duplicated: {key[0]}/{key[1]}")
        actual_coverage.add(key)
    if actual_coverage != expected_coverage:
        missing = sorted(expected_coverage - actual_coverage)
        extra = sorted(actual_coverage - expected_coverage)
        raise ValueError(f"Reader Architecture coverage mismatch: missing={missing} extra={extra}")

    requirements = [row["requirement_id"] for row in payload["reader_requirements"]]
    if len(requirements) != len(set(requirements)):
        raise ValueError("Reader requirements must be unique")
    expected_requirements = _required_reader_requirements(profile)
    if set(requirements) != expected_requirements:
        raise ValueError(
            "Reader requirement set differs from Profile contract: "
            f"expected={sorted(expected_requirements)} actual={sorted(requirements)}"
        )
    if not isinstance(payload.get("authored_by"), str) or not payload["authored_by"].strip():
        raise ValueError("Reader Manifest authored_by required")
    core.parse_instant(payload["recorded_at"])

    # #434: a FULFILLED author assertion is only an accountability claim.
    # Deterministically prove that every claimed LONGFORM location resolves to
    # an exact, non-empty reader-facing TeX block. Editorial adequacy is then
    # judged by the required semantic review against those same exact blocks.
    fidelity.validate_reader_fidelity(
        source_path.read_text(encoding="utf-8"),
        architecture,
        payload["architecture_coverage"],
        payload["reader_requirements"],
        profile["publication_profile"],
    )

    # #434 / #491: Pre-publication reader-surface gate: fail fast before
    # expensive TeX/layout/PDF compilation or candidate assembly if reader-facing
    # text contains prohibited internal pipeline/screening/architecture leakage.
    actual_suppressions = suppressions
    if actual_suppressions is None:
        source_root_rel = profile.get("paths", {}).get("source_root")
        if source_root_rel:
            sup_path = (
                repo_root
                / source_root_rel
                / "publication"
                / "v2"
                / "reader-surface-suppressions-v2.json"
            )
            if sup_path.is_file():
                actual_suppressions = core.load_json(sup_path)
    surface_gate.validate_manuscript_surface(
        repo_root, payload, suppressions=actual_suppressions
    )
    return source_path, profile, architecture_path


def build_manuscript_manifest(
    repo_root: Path,
    issue_id: str,
    production_profile_path: Path,
    architecture_path: Path,
    architecture_approval_path: Path,
    primary_source_path: Path,
    supporting_files: list[dict[str, Any]],
    architecture_coverage: list[dict[str, Any]],
    reader_requirements: list[dict[str, Any]],
    authored_by: str,
    recorded_at: datetime,
    output_path: Path,
    *,
    suppressions: list[dict[str, Any]] | None = None,
) -> Path:
    profile_path, profile = _profile(repo_root, production_profile_path, issue_id)
    architecture_file, _, approval_file = _architecture_authority(
        repo_root,
        issue_id,
        profile,
        architecture_path,
        architecture_approval_path,
    )
    source = _safe_file(repo_root, primary_source_path, "reader-facing primary source")
    support_rows: list[dict[str, Any]] = []
    for row in supporting_files:
        if not isinstance(row, dict) or set(row) != {"role", "path"}:
            raise ValueError("supporting_files inputs must contain role/path")
        value = _sized_artifact(repo_root, _input_path(repo_root, row["path"]))
        support_rows.append({"role": row["role"], **value})
    base = {
        "schema_version": "2.0-rc1",
        "issue_id": issue_id,
        "research_profile": profile["research_profile"],
        "publication_profile": profile["publication_profile"],
        "status": "READER_FACING_AUTHORED",
        "production_profile": _artifact(repo_root, profile_path),
        "architecture": _artifact(repo_root, architecture_file),
        "architecture_approval": _artifact(repo_root, approval_file),
        "primary_source": _sized_artifact(repo_root, source),
        "supporting_files": support_rows,
        "architecture_coverage": architecture_coverage,
        "reader_requirements": reader_requirements,
        "authored_by": authored_by,
        "recorded_at": core.iso_utc(recorded_at),
    }
    payload = dict(base)
    payload["manifest_sha256"] = core.sha256_object(base)
    schema_gate.validate_instance(
        payload,
        repo_root / MANUSCRIPT_SCHEMA,
        label="Reader Manuscript Manifest",
    )
    _validate_manifest_semantics(repo_root, payload, suppressions=suppressions)
    if output_path.exists():
        raise ValueError(f"refusing to overwrite Reader Manuscript Manifest: {output_path}")
    core.write_json(output_path, payload)
    return output_path


def validate_manuscript_manifest(
    repo_root: Path,
    path: Path,
    *,
    issue_id: str | None = None,
    suppressions: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    payload = schema_gate.load_and_validate_json(
        path,
        repo_root / MANUSCRIPT_SCHEMA,
        label="Reader Manuscript Manifest",
    )
    if issue_id is not None and payload["issue_id"] != issue_id:
        raise ValueError("Reader Manuscript issue_id mismatch")
    base = {
        key: payload[key]
        for key in (
            "schema_version",
            "issue_id",
            "research_profile",
            "publication_profile",
            "status",
            "production_profile",
            "architecture",
            "architecture_approval",
            "primary_source",
            "supporting_files",
            "architecture_coverage",
            "reader_requirements",
            "authored_by",
            "recorded_at",
        )
    }
    if payload["manifest_sha256"] != core.sha256_object(base):
        raise ValueError("Reader Manuscript content digest mismatch")
    _validate_manifest_semantics(repo_root, payload, suppressions=suppressions)
    return payload


def _extra_review_checks(
    repo_root: Path,
    profile: dict[str, Any],
    review_kind: str,
) -> set[str]:
    contract = core.load_json(repo_root / REVIEW_CONTRACT)
    if contract.get("schema_version") != "2.0-rc1":
        raise ValueError("publication review contract schema_version invalid")
    lane = "semantic" if review_kind == "SEMANTIC_EDITORIAL" else "visual"
    result: set[str] = set()
    for section in (
        contract.get("core"),
        contract.get("research_profiles", {}).get(profile["research_profile"]),
        contract.get("publication_profiles", {}).get(profile["publication_profile"]),
    ):
        if not isinstance(section, dict) or not isinstance(section.get(lane), list):
            raise ValueError(f"publication review contract missing {lane} Profile lane")
        for check_id in section[lane]:
            if not isinstance(check_id, str) or not check_id.strip() or check_id in result:
                raise ValueError(f"publication review contract check invalid/duplicate: {check_id}")
            result.add(check_id)
    return result


def _expected_review_checks(
    repo_root: Path,
    profile: dict[str, Any],
    review_kind: str,
) -> set[str]:
    cfg = core.load_json(repo_root / core.DEFAULT_CONFIG)
    expected = quality.expected_checks(
        cfg,
        profile["research_profile"],
        profile["publication_profile"],
    )
    kind = "AGENT_SEMANTIC" if review_kind == "SEMANTIC_EDITORIAL" else "AGENT_VISUAL"
    result = {check_id for check_id, value in expected.items() if value == kind}
    extras = _extra_review_checks(repo_root, profile, review_kind)
    if result & extras:
        raise ValueError(
            f"publication review contract duplicates existing quality check IDs: {sorted(result & extras)}"
        )
    return result | extras


def _bound_architecture_for_review(
    repo_root: Path,
    manuscript: dict[str, Any],
) -> dict[str, Any]:
    architecture_path = _validate_artifact_ref(
        repo_root,
        manuscript["architecture"],
        "Review Architecture",
    )
    return schema_gate.load_and_validate_json(
        architecture_path,
        repo_root / ARCHITECTURE_SCHEMA,
        label="Review Architecture",
    )


def build_review_record(
    repo_root: Path,
    manuscript_path: Path,
    pdf_path: Path,
    page_count: int,
    review_kind: str,
    checks: list[dict[str, Any]],
    reviewed_by: str,
    recorded_at: datetime,
    output_path: Path,
) -> Path:
    if review_kind not in {"SEMANTIC_EDITORIAL", "VISUAL"}:
        raise ValueError("review_kind invalid")
    if not isinstance(page_count, int) or page_count < 1:
        raise ValueError("Publication Review page_count must be positive")
    manuscript_file = _safe_file(repo_root, manuscript_path, "Reader Manuscript Manifest")
    manuscript = validate_manuscript_manifest(repo_root, manuscript_file)
    profile_path = _validate_artifact_ref(
        repo_root,
        manuscript["production_profile"],
        "Review Production Profile",
    )
    _, profile = _profile(repo_root, profile_path, manuscript["issue_id"])
    source = _validate_artifact_ref(
        repo_root,
        manuscript["primary_source"],
        "Review reader source",
        sized=True,
    )
    pdf = _safe_file(repo_root, pdf_path, "reviewed publication PDF")
    actual_page_count = _exact_pdf_page_count(pdf)
    if page_count != actual_page_count:
        raise ValueError(
            f"Publication Review page_count does not match exact PDF bytes: "
            f"asserted={page_count} actual={actual_page_count}"
        )
    expected = _expected_review_checks(repo_root, profile, review_kind)
    actual = [row.get("check_id") for row in checks if isinstance(row, dict)]
    if set(actual) != expected or len(actual) != len(set(actual)):
        raise ValueError(
            f"{review_kind} review family incomplete: expected={sorted(expected)} "
            f"actual={sorted(str(x) for x in actual)}"
        )
    if not reviewed_by.strip():
        raise ValueError("Publication Review reviewed_by required")

    architecture = _bound_architecture_for_review(repo_root, manuscript)
    fidelity.validate_review_depth(
        profile,
        architecture,
        manuscript,
        actual_page_count,
        checks,
        review_kind,
    )

    base = {
        "schema_version": "2.0-rc1",
        "issue_id": manuscript["issue_id"],
        "research_profile": profile["research_profile"],
        "publication_profile": profile["publication_profile"],
        "review_kind": review_kind,
        "status": "PASSED",
        "production_profile": _artifact(repo_root, profile_path),
        "reader_manuscript": _artifact(repo_root, manuscript_file),
        "source": _sized_artifact(repo_root, source),
        "pdf": _sized_artifact(repo_root, pdf),
        "page_count": actual_page_count,
        "checks": checks,
        "reviewed_by": reviewed_by,
        "recorded_at": core.iso_utc(recorded_at),
    }
    payload = dict(base)
    payload["review_sha256"] = core.sha256_object(base)
    schema_gate.validate_instance(
        payload,
        repo_root / REVIEW_SCHEMA,
        label="Publication Review Record",
    )
    if output_path.exists():
        raise ValueError(f"refusing to overwrite Publication Review Record: {output_path}")
    core.write_json(output_path, payload)
    validate_review_record(repo_root, output_path, expected_kind=review_kind)
    return output_path


def validate_review_record(
    repo_root: Path,
    path: Path,
    *,
    issue_id: str | None = None,
    expected_kind: str | None = None,
) -> dict[str, Any]:
    payload = schema_gate.load_and_validate_json(
        path,
        repo_root / REVIEW_SCHEMA,
        label="Publication Review Record",
    )
    if issue_id is not None and payload["issue_id"] != issue_id:
        raise ValueError("Publication Review issue_id mismatch")
    if expected_kind is not None and payload["review_kind"] != expected_kind:
        raise ValueError("Publication Review kind mismatch")
    base = {
        key: payload[key]
        for key in (
            "schema_version",
            "issue_id",
            "research_profile",
            "publication_profile",
            "review_kind",
            "status",
            "production_profile",
            "reader_manuscript",
            "source",
            "pdf",
            "page_count",
            "checks",
            "reviewed_by",
            "recorded_at",
        )
    }
    if payload["review_sha256"] != core.sha256_object(base):
        raise ValueError("Publication Review content digest mismatch")
    manuscript_path = _validate_artifact_ref(
        repo_root,
        payload["reader_manuscript"],
        "Review Reader Manuscript",
    )
    manuscript = validate_manuscript_manifest(
        repo_root,
        manuscript_path,
        issue_id=payload["issue_id"],
    )
    profile_path = _validate_artifact_ref(
        repo_root,
        payload["production_profile"],
        "Review Production Profile",
    )
    _, profile = _profile(repo_root, profile_path, payload["issue_id"])
    if (
        payload["research_profile"] != profile["research_profile"]
        or payload["publication_profile"] != profile["publication_profile"]
        or manuscript["research_profile"] != profile["research_profile"]
        or manuscript["publication_profile"] != profile["publication_profile"]
    ):
        raise ValueError("Publication Review Profile identity mismatch")
    source = _validate_artifact_ref(repo_root, payload["source"], "Review source", sized=True)
    manuscript_source = _validate_artifact_ref(
        repo_root,
        manuscript["primary_source"],
        "Manifest source",
        sized=True,
    )
    if source.resolve() != manuscript_source.resolve() or payload["source"] != manuscript["primary_source"]:
        raise ValueError("Publication Review does not bind exact Reader Manuscript source")
    pdf = _validate_artifact_ref(repo_root, payload["pdf"], "Review PDF", sized=True)
    actual_page_count = _exact_pdf_page_count(pdf)
    if payload["page_count"] != actual_page_count:
        raise ValueError(
            f"Publication Review page_count does not match exact PDF bytes: "
            f"recorded={payload['page_count']} actual={actual_page_count}"
        )
    expected = _expected_review_checks(repo_root, profile, payload["review_kind"])
    actual = [row["check_id"] for row in payload["checks"]]
    if set(actual) != expected or len(actual) != len(set(actual)):
        raise ValueError("Publication Review check family differs from bound Profile")

    architecture = _bound_architecture_for_review(repo_root, manuscript)
    fidelity.validate_review_depth(
        profile,
        architecture,
        manuscript,
        actual_page_count,
        payload["checks"],
        payload["review_kind"],
    )
    core.parse_instant(payload["recorded_at"])
    return payload


def build_reader_surface_gate(
    repo_root: Path,
    manuscript_path: Path,
    semantic_review_path: Path,
    *,
    suppressions_path: Path | None = None,
    output_path: Path | None = None,
    evaluated_by: str = "Core v2 Pre-Publication Reader-Surface Gate",
    recorded_at: datetime | None = None,
    state_path: Path | None = None,
) -> Path:
    manuscript_file = _safe_file(repo_root, manuscript_path, "Reader Manuscript Manifest")
    manuscript = validate_manuscript_manifest(repo_root, manuscript_file)
    validated_sem = surface_gate.load_and_validate_reader_surface_semantic_review(
        repo_root,
        semantic_review_path,
        expected_issue_id=manuscript["issue_id"],
        expected_publication_profile=manuscript["publication_profile"],
        require_pass=True,
    )
    surface_sha = validated_sem["surface_sha256"]
    surface_path = validated_sem["surface_path"]
    reviewed_by = validated_sem["reviewed_by"]
    recorded_at = validated_sem["recorded_at"]
    review_sha = validated_sem["review_sha256"]

    suppressions: list[dict[str, Any]] = []
    if suppressions_path is not None and suppressions_path.is_file():
        suppressions = core.load_json(suppressions_path)
    else:
        profile_path = _validate_artifact_ref(repo_root, manuscript["production_profile"], "Review Production Profile")
        _, profile = _profile(repo_root, profile_path, manuscript["issue_id"])
        source_root_rel = profile.get("paths", {}).get("source_root")
        if source_root_rel:
            auto_sup = repo_root / source_root_rel / "publication" / "v2" / "reader-surface-suppressions-v2.json"
            if auto_sup.is_file():
                suppressions = core.load_json(auto_sup)

    semantic_authority = {
        "status": "PASSED",
        "decision": "PASS",
        "reviewed_by": reviewed_by,
        "surface_path": surface_path,
        "surface_sha256": surface_sha,
        "recorded_at": recorded_at,
        "review_path": _rel(repo_root, semantic_review_path),
        "review_sha256": review_sha,
        "summary": "Bound semantic review passed",
    }

    out = output_path
    if out is None:
        source_root_path = repo_root / manuscript["production_profile"]["path"]
        _, prof = _profile(repo_root, source_root_path, manuscript["issue_id"])
        src_root = prof.get("paths", {}).get("source_root", f"sources/{manuscript['issue_id']}")
        out = repo_root / src_root / "publication" / "v2" / "reader-surface-gate-v2.json"

    surface_gate.evaluate_reader_surface_gate(
        repo_root,
        manuscript_file,
        semantic_authority=semantic_authority,
        suppressions=suppressions,
        evaluated_by=evaluated_by,
        recorded_at=recorded_at or datetime.now(timezone.utc),
        output_path=out,
        state_path=state_path,
    )
    return out

